services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MY_MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MY_MONGO_INITDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MY_MONGO_INITDB_PASSWORD}
    ports:
      - "${MONGODB_DOCKER_PORT}:${MONGODB_LOCAL_PORT}"

  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    healthcheck:
      test: [ "CMD", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      - postgres
      - mongodb
    restart: on-failure
    image: smida
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://postgres:${POSTGRESQL_DOCKER_PORT}/${POSTGRESQL_DATABASE}",
        "spring.datasource.username": "${POSTGRESQL_USER}",
        "spring.datasource.password": "${POSTGRESQL_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",        
      }'
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: ${MONGODB_LOCAL_PORT}
      SPRING_DATA_MONGODB_DATABASE: ${MY_MONGO_INITDB_DATABASE}
      SPRING_DATA_MONGODB_USERNAME: ${MY_MONGO_INITDB_USERNAME}
      SPRING_DATA_MONGODB_PASSWORD: ${MY_MONGO_INITDB_PASSWORD}
      SPRING_SERVER_PORT: ${SPRING_DOCKER_PORT}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
